### ISSUE TITLE
请问为什么main方案运行时Power Allocation的cvx运算部分会报错呢？传输速率计算出现复常数问题您遇到过吗？

### ISSUE THREAD

**Issue by yyz0813** [qlt315/NOMA-MEC-IoVT#1]

**Comment by qlt315** [comment]
谢谢你的提问！我自己重新跑了一下也出现了同样的问题，发现是因为CVX求解精度导致有几率使得求出来的功率是负数，然后使得log运算里的数值为负数，从而log得出来的结果为复数，然后导致CVX运算报错。我的解决方法是把最小允许发射功率调大一点，保证CVX求解出来不是负数。

具体方法是把power_allocation_MM.m里面的P_min变量调大，例如从原来的0.00001变为0.01。

**Comment by yyz0813** [comment]
万分感谢您的回信！学到了！问题得到了解决！但十分抱歉，我依然有疑问的是这种解决方法仅适用于main_Hungarian和main_Gale_Shapley两种方案，在main_BellmanFord、main_BellmanFord和main_BellmanFord三种用到图论搜索负环的方案中，问题仍没有得到解决，在邻接矩阵生成的部分，依然有传输速率计算变量无效的报错，请问大佬这是什么原因呢？


（另外，我拜读了您在边缘计算领域丰富傲人的成果，不知道是否方便了解您的联系方式，因为我是研究这个方向的一名哈工程的研究生，所以就想试着争取一下，看看能否有机会能在大佬空闲时候帮助解答一些困惑，如果可以是我的荣幸！）


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qlt315/NOMA-MEC-IoVT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月7日(星期五) 中午11:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qlt315/NOMA-MEC-IoVT] 请问为什么main方案运行时Power Allocation的cvx运算部分会报错呢？传输速率计算出现复常数问题您遇到过吗？ (Issue #1)





 
谢谢你的提问！我自己重新跑了一下也出现了同样的问题，发现是因为CVX求解精度导致有几率使得求出来的功率是负数，然后使得log运算里的数值为负数，从而log得出来的结果为复数，然后导致CVX运算报错。我的解决方法是把最小允许发射功率调大一点，保证CVX求解出来不是负数。
 
具体方法是把power_allocation_MM.m里面的P_min变量调大，例如从原来的0.00001变为0.01。

**Comment by yyz0813** [comment]
万分感谢您的回信！问题得到了解决！但十分抱歉，我依然有疑问的是这种解决方法仅适用于main_Hungarian和main_Gale_Shapley两种方案，在main_BellmanFord、main_BellmanFord和main_BellmanFord三种用到图论搜索负环的方案中，问题仍没有得到解决，在邻接矩阵生成的部分，依然有传输速率计算变量无效的报错，请问大佬这是什么原因呢？

**Comment by qlt315** [comment]
你好！感觉还是CVX的问题。因为CVX求解精度的关系有时候会出现不满足约束出现负数以及无解的情况，你不妨采取以下的措施试试：
（1）更换求解器，从cvx_solver SDPT3 改为 cvx_solver SeDuMi
（2）power_allocation_MM.m里面的P_min再调小一点，例如0.003
（3）把CVX从2.x版本升级到3.0，因为CVX3.0可以支持log2函数，不用再用逼近的方法模拟log2，这样也可以提升求解精度。然后把power_allocation_MM.m里面相应代码改为:
R_tilde_2 = Bandwidth * log2(R_tilde_2_sum + Sigma_n^2); 
R_tilde_1 = Bandwidth * log2(R_tilde_1_sum + Sigma_n^2);

**Comment by yyz0813** [comment]
打扰您了，请问在您的代码哪个部分是体现不同子信道之间进行正交频分多址(OFDMA)的呢？我并没有找到对应的代码部分~

**Comment by qlt315** [comment]
同学你好！本文采用的是非正交多址接入（NOMA）方式进行数据传输，然后考虑了NOMA传输中的用户分组问题。对于相同组内的用户，则采用相同的频率资源传输；而对于不同组的用户则是用OFDMA传输。OFDMA具体的表现形式在于SINR的计算上：对于一个特定用户来说，他所受到的干扰仅仅来自于同组用户，其他组的用户由于用的是与之正交的频率资源，所以对这个特定用户没有干扰。

**Comment by yyz0813** [comment]
您好！请问您提供的代码运行之后的结果图与对应文献吻合吗？我尝试运行之后发现本文方案以及对比算法方案的加权平均总延迟D_total_aver均为inf无穷大，这也就导致我无法看出算法仿真性能对比效果，我无法画出文献的算法对比图，您可以为我解答一下吗？非常感谢！

**Comment by qlt315** [comment]
谢谢同学的反馈，我目前在忙一些其他的事情。正好这篇paper的审稿意见已经下来了，我会过几天来看看代码，到时候再给你答复。

**Comment by qlt315** [comment]
同学你好 我已经上传了新的代码，你看看还有之前的问题么。

此外，运行的结果和原文不一定完全一致，因为我们采取的是运行多次取平均的做法，有一些随机性的影响。

**Comment by SUN-bef-dev** [comment]
大佬，我发现System_init.m文件里“Sigma_n = 3.981071705534951e-21*Bandwidth;    % Variance of AWGN (W)=-174dBm/Hz”，这里的值是不是写错了呀，根据您的备注，应该是3.9811e-18吧！

**Comment by qlt315** [comment]
谢谢同学的评论。我在 https://www.elecfans.com/tools/dbm.htm 下进行dBm和W的换算得到的结果似乎是3.98107170553495e-21 W 你是不是把dBm和dBW弄混了😄

**Comment by SUN-bef-dev** [comment]
是我的问题哈哈，我用的matlab的函数db2pow，单位应该是dB，抱歉
