### ISSUE TITLE
对应的文章

### ISSUE THREAD

**Issue by 21111535** [qlt315/NOMA-MEC-IoVT#2]
请问代码对应的文章发表了吗，我直接搜索这个论文题目没找到对应的文章呢（Joint Transmission and Resource Optimization in NOMA-assisted IoVT with Mobile Edge Computing），谢谢您！

**Comment by qlt315** [comment]
这篇文章目前还在审稿流程中，但是我们在在Techxiv上传了预印本的版本：https://www.techrxiv.org/articles/preprint/Joint_Transmission_and_Resource_Optimization_in_NOMA-assisted_IoVT_with_Mobile_Edge_Computing/22679962
