### ISSUE TITLE
论文

### ISSUE THREAD

**Issue by zys459183956** [qlt315/NOMA-MEC-IoVT#3]
您好，论文现在审完了吗，或者从哪能看到您的文章，可以发一份到邮箱459183956@qq.com,非常感谢

**Comment by qlt315** [comment]
同学你好，论文目前还在审稿阶段，我已经将预印本上传到了TechRxiv，你可以在下面的网址看到目前的文章：
https://www.techrxiv.org/articles/preprint/Joint_Transmission_and_Resource_Optimization_in_NOMA-assisted_IoVT_with_Mobile_Edge_Computing/22679962

**Comment by zys459183956** [comment]
谢谢已收到
