### ISSUE TITLE
变量未定义

### ISSUE THREAD

**Issue by zys459183956** [qlt315/NOMA-MEC-IoVT#4]
您好，Association_update
未定义函数或变量 'Neg_ring'
是只能用2023吗，我用的2019a显示错误，有好几个模块都是这样

**Comment by qlt315** [comment]
同学你好 这个模块是不能单独运行的，虽然没有写成函数的形式，但这个模块的功能和一个函数一致，要依赖于主程序中所找到的负环才能运行，所以如果你直接运行这个m文件就会出现未定义函数或变量 'Neg_ring'的错误
