### ISSUE TITLE
我在 Adjacency.m 中遇到错误

### ISSUE THREAD

**Issue by AedyVader** [qlt315/NOMA-MEC-IoVT#5]
我已遵循您对之前其他问题的回复中的所有建议，但遇到了错误:

Error using  +  (line 29)
Disciplined convex programming error:
   Invalid operation: {NaN} + {real affine}

Error in power_allocation_MM (line 123)
        R_tilde_1_sum = R_tilde_2_sum + abs(sum(Channel_coff(:,j).*A(:,j)))^2*P_cvx(j);

Error in Adjacency_init (line 173)
                P = power_allocation_MM(A_sim);

Error in main_BellmanFord (line 26)
Adjacency_init;

你能帮我解决这个问题吗？请回答这个问题

**Comment by qlt315** [comment]
Hi 你好，这个报错似乎并不是每次运行都会出现。请检查出错时R_tilde_2_sum是否是NaN，如果是的话，请在R_tilde_1_sum = R_tilde_2_sum + abs(sum(Channel_coff(:,j).A(:,j)))^2P_cvx(j);前加一个判断，当R_tilde_2_sum为NaN时就不要加上这一项。

**Comment by AedyVader** [comment]
我已经检查并尝试再次运行它，它似乎工作正常。带来不便敬请谅解。最后一个问题，运行 10 次迭代需要多长时间，因为运行模拟确实需要一些时间。

**Comment by qlt315** [comment]
Hi 你好，运行10次迭代所需要的时间和设置的用户数和AP数有关，因为其影响邻接矩阵的大小，而绝大部分运算的时间都花在了邻接矩阵的计算和更新上。一般来说，对于较小的用户数和AP数，运行10次迭代要几个小时。

**Comment by AedyVader** [comment]
我明白了。谢谢你的解释。祝你好运。
