### ISSUE TITLE
运行功率分配函数（power_allocation_MM.m）问题

### ISSUE THREAD

**Issue by senrio1** [qlt315/NOMA-MEC-IoVT#6]
这是cvx的问题吗?应该怎么解决?请教一下作者，非常非常感谢!!
matlab出现报错:
main_BellmanFord
未定义与 'cvx' 类型的输入参数相对应的函数 'log2'。

出错 power_allocation_MM (第 123 行)
        R_tilde_1 = Bandwidth*log2(R_tilde_1_sum + Sigma_n^2); % first term of Eq. (12)

出错 main_BellmanFord (第 8 行)
P = power_allocation_MM(A);

**Comment by qlt315** [comment]
Hi 同学你好，请确保已经安装**CVX3.0**，CVX2.0里面是没有log2的。

**Comment by senrio1** [comment]
> Hi 同学你好，请确保已经安装**CVX3.0，CVX2.0**里面是没有log2的。

谢谢学长，我已经装好了CVX3.0，但是运行main函数仍会报错，应该是在Adjacency_init_nearest或者Adjacency_init中运行power_allocation_MM时使用CVX出错，请教一下学长当时您出现这个问题的时候应该如何解决呢?非常感谢!
matlab报错:
错误使用  +  (第 29 行)
Disciplined convex programming error:
   Invalid operation: {NaN} + {real affine}

出错 power_allocation_MM (第 121 行)
        R_tilde_1_sum = R_tilde_2_sum + abs(sum(Channel_coff(:,j).*A(:,j)))^2*P_cvx(j);

出错 Adjacency_init_nearest (第 109 行)
                P = power_allocation_MM(A_sim);

出错 main_Nearest_Offloading (第 23 行)
Adjacency_init_nearest;

**Comment by qlt315** [comment]
Hi 同学你好，你可以参考一下Issue #5的回答:)

**Comment by senrio1** [comment]
> Hi 同学你好，你可以参考一下Issue #5的回答:)

好的好的，非常感谢学长的耐心回答!谢谢!

**Comment by senrio1** [comment]
学长，还想请问一下运行power_allocation_MM出现一下报错的原因会是什么呢？好像并不是每轮循环都会有这个报错，但是运行主函数经过多次循环确实会存在这个问题，请问一下有没有方法解决呢?非常感谢!

错误使用  -  (第 27 行)
Disciplined convex programming error:
   Invalid operation: {real affine} - {NaN}

出错 power_allocation_MM (第 142 行)
            R_tilde_3_sum_1 = R_tilde_3_sum_1 +
            abs(sum(Channel_coff(:,Beh_user(i)).*A(:,Beh_user(i))))^2*(P_cvx(Beh_user(i))-P_last(Beh_user(i))); % molecule
            of the third term of Eq. (12)

出错 Adjacency_init (第 36 行)
                P = power_allocation_MM(A_sim);

出错 main_BellmanFord (第 23 行)
Adjacency_init;

> Hi 同学你好，你可以参考一下Issue #5的回答:)

**Comment by qlt315** [comment]
应该是Beh_user这个数组有时候会是空，因为有些用户可能不存在在该用户之后解码的用户。你可以在出现这种NaN情况的前面都加一个判断
